### ISSUE TITLE
sodalite.nodes.OpenStack.VM fails due to invalid node_exporter JSON template

### ISSUE THREAD

**Issue by mihaTrajbaric** [SODALITE-EU/iac-modules#9]
When creating OpenStack VM, it fails with:

```json
{
    "hosts": {
        "server": {
            "_ansible_no_log": false,
            "action": "template",
            "changed": false,
            "failed": true,
            "msg": "AnsibleUndefinedVariable: 'id' is undefined"
        }
    },
    "task": {
        "duration": {
            "end": "2021-03-22T21:46:03.367731Z",
            "start": "2021-03-22T21:46:01.811465Z"
        },
        "id": "d36be4c0-bbf1-e12b-1159-000000000038",
        "name": "Generating JSON object into a node_exporter.json file"
    }
}
```

**Comment by jramosrivas** [comment]
I think I fixed it, I cannot test it at the moment.

**Comment by mihaTrajbaric** [comment]
Hi, thank you for the fix, unfortunately, It still failed. I introduced fixes, please review them in my pull request (#11).

Also, next time when introducing changes/fixes, please, do it in a Pull request, so others can review, test and comment.

**Comment by jramosrivas** [comment]
Yes you are right, I apologize, I will do it that way from now on.
